routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\GoogleLoginController;
use App\Http\Controllers\GuestController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LandingPageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LandingPageController::class, 'index'])->name('landingPage');
Route::get('/detail-gazeboo', [LandingPageController::class, 'detailGazeboo'])->name('detail-gazeboo');
Route::get('/detail-food', [LandingPageController::class, 'detailFood'])->name('detail-food');

Route::get('/login/google', [GoogleLoginController::class, 'redirectToProvider'])->name('login-google');
Route::get('/login/google/callback', [GoogleLoginController::class, 'handleProviderCallback']);

Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::get('/register', [AuthController::class, 'register'])->name('register');
Route::post('/register-account', [AuthController::class, 'registerAccount'])->name('register-account');
Route::post('/login-cek', [AuthController::class, 'login'])->name('login-cek');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

Route::get('cart', [CartController::class, 'cart'])->name('cart');
Route::get('add-to-cart/{type}/{id}', [CartController::class, 'addToCart'])->name('add.to.cart');
Route::post('order', [CartController::class, 'order'])->name('cart.order');
Route::patch('update-cart', [CartController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [CartController::class, 'remove'])->name('remove.from.cart');

Route::group(['middleware' => ['auth']], function () {
    Route::get('guest', [GuestController::class, 'index'])->name('guest');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');

    Route::prefix('master')->group(function () {
        Route::prefix('gazeboes')->group(function (){
            Route::get('/', [\App\Http\Controllers\GazebooController::class, 'index'])->name('gazeboo.index');
            Route::get('/create', [\App\Http\Controllers\GazebooController::class, 'create'])->name('gazeboo.create');
            Route::post('/store', [\App\Http\Controllers\GazebooController::class, 'store'])->name('gazeboo.store');
            Route::delete('/delete/{gazeboo}', [\App\Http\Controllers\GazebooController::class, 'destroy'])->name('gazeboo.delete');
            Route::get('/edit/{gazeboo}', [\App\Http\Controllers\GazebooController::class, 'edit'])->name('gazeboo.edit');
            Route::post('/update/{gazeboo}', [\App\Http\Controllers\GazebooController::class, 'update'])->name('gazeboo.update');
            Route::get('/delete-picture/{picture}', [\App\Http\Controllers\GazebooController::class, 'deletePicture'])->name('gazeboo.delete-picture');
        });

        Route::prefix('foods')->group(function (){
            Route::get('/', [\App\Http\Controllers\FoodController::class, 'index'])->name('food.index');
            Route::get('/create', [\App\Http\Controllers\FoodController::class, 'create'])->name('food.create');
            Route::post('/store', [\App\Http\Controllers\FoodController::class, 'store'])->name('food.store');
            Route::delete('/delete/{food}', [\App\Http\Controllers\FoodController::class, 'destroy'])->name('food.delete');
            Route::get('/edit/{food}', [\App\Http\Controllers\FoodController::class, 'edit'])->name('food.edit');
            Route::post('/update/{food}', [\App\Http\Controllers\FoodController::class, 'update'])->name('food.update');
        });
    });

    Route::prefix('transaction')->group(function (){
        Route::prefix('booking')->group(function (){
            Route::get('/', [\App\Http\Controllers\BookingController::class, 'index'])->name('booking.index');
            Route::get('/create', [\App\Http\Controllers\BookingController::class, 'create'])->name('booking.create');
            Route::post('/store', [\App\Http\Controllers\BookingController::class, 'store'])->name('booking.store');
            Route::delete('/delete/{booking}', [\App\Http\Controllers\BookingController::class, 'destroy'])->name('booking.delete');
            Route::get('/edit/{booking}', [\App\Http\Controllers\BookingController::class, 'edit'])->name('booking.edit');
            Route::post('/update/{booking}', [\App\Http\Controllers\BookingController::class, 'update'])->name('booking.update');
            Route::get('/realization/{booking}', [\App\Http\Controllers\BookingController::class, 'realization'])->name('booking.realization');
            Route::get('/approve/{booking}', [\App\Http\Controllers\BookingController::class, 'approve'])->name('booking.approve');
            Route::get('/decline/{booking}', [\App\Http\Controllers\BookingController::class, 'decline'])->name('booking.decline');
            Route::get('/finish/{booking}', [\App\Http\Controllers\BookingController::class, 'finish'])->name('booking.finish');
            Route::get('/export', [\App\Http\Controllers\BookingController::class, 'export'])->name('booking.export');
        });

        Route::prefix('food')->group(function (){
            Route::get('/', [\App\Http\Controllers\TransactionFoodController::class, 'index'])->name('transaction.food.index');
            Route::get('/create', [\App\Http\Controllers\TransactionFoodController::class, 'create'])->name('transaction.food.create');
            Route::post('/store', [\App\Http\Controllers\TransactionFoodController::class, 'store'])->name('transaction.food.store');
            Route::delete('/delete/{trx_id}', [\App\Http\Controllers\TransactionFoodController::class, 'destroy'])->name('transaction.food.delete');
            Route::get('/approve/{trx_id}', [\App\Http\Controllers\TransactionFoodController::class, 'approve'])->name('transaction.food.approve');
            Route::get('/decline/{trx_id}', [\App\Http\Controllers\TransactionFoodController::class, 'decline'])->name('transaction.food.decline');
            Route::get('/finish/{trx_id}', [\App\Http\Controllers\TransactionFoodController::class, 'finish'])->name('transaction.food.finish');
            Route::get('/export', [\App\Http\Controllers\TransactionFoodController::class, 'export'])->name('food.export');
        });
    });

    Route::prefix('/report')->group(function (){
        Route::prefix('/gazeboo')->group(function (){
            Route::get('/finish', [\App\Http\Controllers\ReportGazebooController::class, 'finish'])->name('report.gazeboo.finish');
            Route::get('/decline', [\App\Http\Controllers\ReportGazebooController::class, 'decline'])->name('report.gazeboo.decline');
        });
    });

    Route::get('/server-busyness', [\App\Http\Controllers\ServerBusyController::class, 'index'])->name('server-busyness');

    Route::get('/service', [\App\Http\Controllers\ServiceController::class, 'index'])->name('service.index');

});

app/Models/Gazeboos.php
<?php

namespace App\Models;

use App\Traits\WithPictures;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Gazeboos extends Model
{
    use HasFactory, SoftDeletes, WithPictures;

    const AVAILABLE = 1;
    const NOT_AVAILABLE = 0;

    const GAZEBOO_SINGLE = "Gazeboo Tunggal";
    const GAZEBOO_DOUBLE = "Gazeboo Gandeng";
    const LESEHAN = "Lesehan";
    const PENDOPO = "Pendopo";

    const ACTIVE = 1;
    const NOT_ACTIVE = 0;

    protected $fillable = [
        'number',
        'title',
        'description',
        'price',
        'category',
        'is_active',
        'is_available'
    ];

    public function bookings(){
        return $this->hasMany(Booking::class, 'gazeboo_id', 'id');
    }

    public function getActiveStatusAttribute(){
        return $this->is_active ? 'Aktif' : 'Non Aktif';
    }

    public function scopeActive($query){
        return $query->where('is_active', true);
    }

    public function getBookingStatusAttribute(){
        return $this->is_available ? 'Tersedia' : 'Booked';
    }

    public function scopeAvailable($query){
        return $query->where('is_available', true);
    }

    public function scopeBooked($query){
        return $query->where('is_available', false);
    }
}

app/Models/Pictures.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pictures extends Model
{
    use HasFactory;

    protected $fillable = [
        'pictureable_type',
        'pictureable_id',
        'file_name',
        'caption',
        'path'
    ];

    public function getUrlAttribute()
    {
        if (is_null($this->path)) {
            return asset('images/logo_watermark.jpg');
        }

        return asset('storage/'.$this->path.'/'.$this->file_name);
    }
}

app/Http/Controllers/GazebooController.php
<?php

namespace App\Http\Controllers;

use App\Models\Gazeboos;
use App\Models\Pictures;
use Illuminate\Http\Request;

class GazebooController extends Controller
{
    public function index(){
        $indexLink = route('gazeboo.index');
        $createLink = route('gazeboo.create');

        $gazeboes = Gazeboos::latest()->paginate(10);

        return view('master.gazeboo.index', compact('indexLink', 'createLink', 'gazeboes'));
    }

    public function create(){
        $indexLink = route('gazeboo.index');
        $storeLink = route('gazeboo.store');

        return view('master.gazeboo.create', compact('indexLink', 'storeLink'));
    }

    public function store(Request $request){
        $gazeboo = Gazeboos::create($request->all());

        insert_pictures($request->images, $gazeboo);

        return redirect()->route('gazeboo.index');
    }

    public function edit(Gazeboos $gazeboo){
        $indexLink = route('gazeboo.index');
        $updateLink = route('gazeboo.update', $gazeboo);

        return view('master.gazeboo.edit', compact('updateLink', 'indexLink', 'gazeboo'));
    }

    public function update(Gazeboos $gazeboo, Request $request){
        $gazeboo->update($request->all());

        if (!empty($request->images_old)){
            foreach ($request->images_old as $key => $image){
                $picture = Pictures::find($request->id_images_old[$key]);
                \Illuminate\Support\Facades\Storage::disk('public')->put($picture->path, $image);

                $picture->update([
                    'file_name' => $image->hashName(),
                ]);
            }
        }

        if (isset($request->images)){
            insert_pictures($request->images, $gazeboo);
        }

        return redirect()->route('gazeboo.index');
    }

    public function destroy(Gazeboos $gazeboo){
        $gazeboo->delete();

        return redirect()->back();
    }

    public function deletePicture(Pictures $picture){
        $picture->delete();
        return back();
    }
}

resources/views/master/gazeboo/create.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Tambah Gazeboo</h1>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                    <div class="card">
                        <div class="card-body">

                            <form action="{{ $storeLink }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label for="number-input">Nomor</label>
                                        <input type="text" class="form-control" name="number" id="number-input" placeholder=""  autocomplete="off" required>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="title-input">Judul</label>
                                        <input type="text" name="title" class="form-control" id="title-input" placeholder="" autocomplete="off" required>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label for="category-input">Kategori</label>
                                        <select class="custom-select select2" id="category" name="category" required>
                                            <option value="{{ \App\Models\Gazeboos::GAZEBOO_SINGLE }}">{{ \App\Models\Gazeboos::GAZEBOO_SINGLE }}</option>
                                            <option value="{{ \App\Models\Gazeboos::GAZEBOO_DOUBLE }}">{{ \App\Models\Gazeboos::GAZEBOO_DOUBLE }}</option>
                                            <option value="{{ \App\Models\Gazeboos::LESEHAN }}">{{ \App\Models\Gazeboos::LESEHAN }}</option>
                                            <option value="{{ \App\Models\Gazeboos::PENDOPO }}">{{ \App\Models\Gazeboos::PENDOPO }}</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label for="price-input">Harga</label>
                                        <input type="text" class="form-control" name="price" id="price-input" placeholder=""  autocomplete="off" required>
                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-group">
                                        <label for="is-active-input">Status</label>
                                        <select class="custom-select select2" id="is_active" name="is_active" required>
                                            <option value="{{ \App\Models\Gazeboos::ACTIVE }}">{{ \App\Models\Gazeboos::ACTIVE == true ?  'Aktif' : 'Tidak Aktif' }}</option>
                                            <option value="{{ \App\Models\Gazeboos::NOT_ACTIVE }}">{{ \App\Models\Gazeboos::NOT_ACTIVE == true ?  'Aktif' : 'Tidak Aktif' }}</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="description-input">Deskripsi</label>
                                    <textarea style="min-height: 120px" name="description" rows="10" class="form-control" id="description-input"  required></textarea>
                                </div>

                                <div class="form-group col-xs-12 col-md-3">
                                    <input type="file" name="images[]" id="input-file-now" class="dropify" accept="image/*" required/>
                                </div>
                                <div class="form-group col-xs-12 col-md-3">
                                    <input type="file" name="images[]" id="input-file-now" class="dropify" accept="image/*"/>
                                </div>
                                <div class="form-group col-xs-12 col-md-3">
                                    <input type="file" name="images[]" id="input-file-now" class="dropify" accept="image/*" />
                                </div>
                                <div class="form-group col-xs-12 col-md-3">
                                    <input type="file" name="images[]" id="input-file-now" class="dropify" accept="image/*" />
                                </div>


                        </div>
                                <a href="{{ $indexLink }}" type="button" class="btn btn-danger"><i class="fas fa-times"></i> Batal</a>
                                <button type="submit" class="btn btn-success"><i class="fas fa-paper-plane"></i> Kirim</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('css')
    <link href="{{ asset('css/dropify.css') }}" rel="stylesheet">
@endpush
@push('javascript')
    <script src="{{ asset('js/dropify.min.js') }}"></script>
    <script>
        $(function () {
            $('.dropify').dropify();
        });
    </script>
@endpush

resources/views/master/gazeboo/edit.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Edit Gazeboo #{{ strtoupper($gazeboo->number) }}</h1>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                    <div class="card">
                        <div class="card-body">

                            <form action="{{ $updateLink }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="number-input">Nomor</label>
                                            <input type="text" class="form-control" name="number" id="number-input" value="{{ $gazeboo->number }}" autocomplete="off" placeholder="" required>
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="title-input">Judul</label>
                                            <input type="text" name="title" class="form-control" id="title-input" placeholder="" autocomplete="off" value="{{ $gazeboo->title }}"  required>
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="category-input">Kategori</label>
                                            <select class="custom-select select2" id="category" name="category" required>
                                                <option @if($gazeboo->category == \App\Models\Gazeboos::GAZEBOO_SINGLE ) selected @endif value="{{ \App\Models\Gazeboos::GAZEBOO_SINGLE }}">{{ \App\Models\Gazeboos::GAZEBOO_SINGLE }}</option>
                                                <option @if($gazeboo->category == \App\Models\Gazeboos::GAZEBOO_DOUBLE ) selected @endif value="{{ \App\Models\Gazeboos::GAZEBOO_DOUBLE }}">{{ \App\Models\Gazeboos::GAZEBOO_DOUBLE }}</option>
                                                <option @if($gazeboo->category == \App\Models\Gazeboos::LESEHAN ) selected @endif value="{{ \App\Models\Gazeboos::LESEHAN }}">{{ \App\Models\Gazeboos::LESEHAN }}</option>
                                                <option @if($gazeboo->category == \App\Models\Gazeboos::PENDOPO ) selected @endif value="{{ \App\Models\Gazeboos::PENDOPO }}">{{ \App\Models\Gazeboos::PENDOPO }}</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="is-active-input">Status</label>
                                            <select class="custom-select select2" id="is_active" name="is_active" required>
                                                <option value="{{ \App\Models\Gazeboos::ACTIVE }}" {{ $gazeboo->is_active == \App\Models\Gazeboos::ACTIVE ? 'selected' : '' }}>{{ \App\Models\Gazeboos::ACTIVE == true ?  'Aktif' : 'Tidak Aktif' }}</option>
                                                <option value="{{ \App\Models\Gazeboos::NOT_ACTIVE }}" {{ $gazeboo->is_active == \App\Models\Gazeboos::NOT_ACTIVE ? 'selected' : '' }}>{{ \App\Models\Gazeboos::NOT_ACTIVE == true ?  'Aktif' : 'Tidak Aktif' }}</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="description-input">Deskripsi</label>
                                        <textarea style="min-height: 120px" name="description" rows="10" class="form-control" id="description-input"  required>{{ $gazeboo->description }} </textarea>
                                    </div>

                                    @for($x = 0; $x < count($gazeboo->pictures); $x++)
                                        <div class="form-group col-xs-12 col-md-3">
                                            <input type="hidden" name="id_images_old[]" value="{{ $gazeboo->pictures[$x]->id }}">
                                            <input type="file" name="images_old[{{ $x }}]" id="input-file-now" class="dropify" data-default-file="{{ $gazeboo->pictures[$x]->url }}" accept="image/*"/>
                                            <a href="{{ route('gazeboo.delete-picture', $gazeboo->pictures[$x]->id)}}" class="btn btn-danger btn-block mt-2">Hapus</a>
                                        </div>
                                    @endfor

                                    @for($i = count($gazeboo->pictures); $i <= 3; $i++)
                                        <div class="form-group col-xs-12 col-md-3">
                                            <input type="file" name="images[]" id="input-file-now" class="dropify" accept="image/*"/>
                                        </div>
                                    @endfor

                                </div>
                                <a href="{{ $indexLink }}" type="button" class="btn btn-danger"><i class="fas fa-times"></i> Batal</a>
                                <button type="submit" class="btn btn-success"><i class="fas fa-paper-plane"></i> Kirim</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('css')
    <link href="{{ asset('css/dropify.css') }}" rel="stylesheet">
@endpush
@push('javascript')
    <script src="{{ asset('js/dropify.min.js') }}"></script>
    <script>
        $(function () {
            $('.dropify').dropify();
        });
    </script>
@endpush

resources/views/master/gazeboo/index.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Gazeboo</h1>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-right mb-4">
                                <a href="{{ $createLink }}" type="button" class="btn btn-success"><i class="fas fa-plus"></i> Tambah</a>
                            </div>

                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th scope="col">Nomor</th>
                                            <th scope="col">Judul</th>
                                            <th scope="col">Kategori</th>
                                            <th scope="col">Harga</th>
                                            <th scope="col">Deskripsi</th>
                                            <th scope="col">Gambar</th>
                                            <th scope="col">Ketersediaan</th>
                                            <th scope="col">Status</th>
                                            <th scope="col"><i class="fas fa-cog fa-spin"></i> Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($gazeboes as $gazeboo)
                                            <tr>
                                                <td>{{ $gazeboo->number }}</td>
                                                <td>{{ \Illuminate\Support\Str::limit($gazeboo->title, 100, '...') }}</td>
                                                <td>{{ $gazeboo->category }}</td>
                                                <td>{{ rp_format($gazeboo->price) }}</td>
                                                <td>{{ \Illuminate\Support\Str::limit($gazeboo->description, 100, '...') }}</td>
                                                <td>
                                                    @foreach($gazeboo->pictures as $picture)
                                                        <a href="{{ $picture->url }}" target="_blank"><img src="{{ $picture->url }}" class="img-thumbnail m-1" style="width:50px; display: inline-block"></a>
                                                    @endforeach
                                                </td>
                                                <td>
                                                    <span class="badge badge-{{ $gazeboo->is_available ? 'success' : 'secondary'}}">{{ $gazeboo->booking_status }}</span>
                                                </td>
                                                <td>
                                                    <span class="badge badge-{{ $gazeboo->is_active ? 'success' : 'danger'}}">{{ $gazeboo->active_status }}</span>
                                                </td>
                                                <td>
                                                    <a href="{{ route('gazeboo.edit',$gazeboo->id) }}" class="btn btn-warning mb-1"><i class="fas fa-pen"></i></a>
                                                    <form action="{{ route('gazeboo.delete', $gazeboo) }}" method="POST" onsubmit="return confirm('Anda yakin menghapus data ini?')" style="display: inline !important;">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="float-right">
                                {{ $gazeboes->appends(Request::except('page'))->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection