routes/web.php
<?php

use App\Http\Controllers\CartController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\GoogleLoginController;
use App\Http\Controllers\GuestController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\LandingPageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LandingPageController::class, 'index'])->name('landingPage');
Route::get('/detail-gazeboo', [LandingPageController::class, 'detailGazeboo'])->name('detail-gazeboo');
Route::get('/detail-food', [LandingPageController::class, 'detailFood'])->name('detail-food');

Route::get('/login/google', [GoogleLoginController::class, 'redirectToProvider'])->name('login-google');
Route::get('/login/google/callback', [GoogleLoginController::class, 'handleProviderCallback']);

Route::get('/login', [AuthController::class, 'index'])->name('login');
Route::get('/register', [AuthController::class, 'register'])->name('register');
Route::post('/register-account', [AuthController::class, 'registerAccount'])->name('register-account');
Route::post('/login-cek', [AuthController::class, 'login'])->name('login-cek');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');

Route::get('cart', [CartController::class, 'cart'])->name('cart');
Route::get('add-to-cart/{type}/{id}', [CartController::class, 'addToCart'])->name('add.to.cart');
Route::post('order', [CartController::class, 'order'])->name('cart.order');
Route::patch('update-cart', [CartController::class, 'update'])->name('update.cart');
Route::delete('remove-from-cart', [CartController::class, 'remove'])->name('remove.from.cart');

Route::group(['middleware' => ['auth']], function () {
    Route::get('guest', [GuestController::class, 'index'])->name('guest');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('home', [HomeController::class, 'index'])->name('home');

    Route::prefix('master')->group(function () {
        Route::prefix('gazeboes')->group(function (){
            Route::get('/', [\App\Http\Controllers\GazebooController::class, 'index'])->name('gazeboo.index');
            Route::get('/create', [\App\Http\Controllers\GazebooController::class, 'create'])->name('gazeboo.create');
            Route::post('/store', [\App\Http\Controllers\GazebooController::class, 'store'])->name('gazeboo.store');
            Route::delete('/delete/{gazeboo}', [\App\Http\Controllers\GazebooController::class, 'destroy'])->name('gazeboo.delete');
            Route::get('/edit/{gazeboo}', [\App\Http\Controllers\GazebooController::class, 'edit'])->name('gazeboo.edit');
            Route::post('/update/{gazeboo}', [\App\Http\Controllers\GazebooController::class, 'update'])->name('gazeboo.update');
            Route::get('/delete-picture/{picture}', [\App\Http\Controllers\GazebooController::class, 'deletePicture'])->name('gazeboo.delete-picture');
        });

        Route::prefix('foods')->group(function (){
            Route::get('/', [\App\Http\Controllers\FoodController::class, 'index'])->name('food.index');
            Route::get('/create', [\App\Http\Controllers\FoodController::class, 'create'])->name('food.create');
            Route::post('/store', [\App\Http\Controllers\FoodController::class, 'store'])->name('food.store');
            Route::delete('/delete/{food}', [\App\Http\Controllers\FoodController::class, 'destroy'])->name('food.delete');
            Route::get('/edit/{food}', [\App\Http\Controllers\FoodController::class, 'edit'])->name('food.edit');
            Route::post('/update/{food}', [\App\Http\Controllers\FoodController::class, 'update'])->name('food.update');
        });
    });

    Route::prefix('transaction')->group(function (){
        Route::prefix('booking')->group(function (){
            Route::get('/', [\App\Http\Controllers\BookingController::class, 'index'])->name('booking.index');
            Route::get('/create', [\App\Http\Controllers\BookingController::class, 'create'])->name('booking.create');
            Route::post('/store', [\App\Http\Controllers\BookingController::class, 'store'])->name('booking.store');
            Route::delete('/delete/{booking}', [\App\Http\Controllers\BookingController::class, 'destroy'])->name('booking.delete');
            Route::get('/edit/{booking}', [\App\Http\Controllers\BookingController::class, 'edit'])->name('booking.edit');
            Route::post('/update/{booking}', [\App\Http\Controllers\BookingController::class, 'update'])->name('booking.update');
            Route::get('/realization/{booking}', [\App\Http\Controllers\BookingController::class, 'realization'])->name('booking.realization');
            Route::get('/approve/{booking}', [\App\Http\Controllers\BookingController::class, 'approve'])->name('booking.approve');
            Route::get('/decline/{booking}', [\App\Http\Controllers\BookingController::class, 'decline'])->name('booking.decline');
            Route::get('/finish/{booking}', [\App\Http\Controllers\BookingController::class, 'finish'])->name('booking.finish');
            Route::get('/export', [\App\Http\Controllers\BookingController::class, 'export'])->name('booking.export');
        });

        Route::prefix('food')->group(function (){
            Route::get('/', [\App\Http\Controllers\TransactionFoodController::class, 'index'])->name('transaction.food.index');
            Route::get('/create', [\App\Http\Controllers\TransactionFoodController::class, 'create'])->name('transaction.food.create');
            Route::post('/store', [\App\Http\Controllers\TransactionFoodController::class, 'store'])->name('transaction.food.store');
            Route::delete('/delete/{trx_id}', [\App\Http\Controllers\TransactionFoodController::class, 'destroy'])->name('transaction.food.delete');
            Route::get('/approve/{trx_id}', [\App\Http\Controllers\TransactionFoodController::class, 'approve'])->name('transaction.food.approve');
            Route::get('/decline/{trx_id}', [\App\Http\Controllers\TransactionFoodController::class, 'decline'])->name('transaction.food.decline');
            Route::get('/finish/{trx_id}', [\App\Http\Controllers\TransactionFoodController::class, 'finish'])->name('transaction.food.finish');
            Route::get('/export', [\App\Http\Controllers\TransactionFoodController::class, 'export'])->name('food.export');
        });
    });

    Route::prefix('/report')->group(function (){
        Route::prefix('/gazeboo')->group(function (){
            Route::get('/finish', [\App\Http\Controllers\ReportGazebooController::class, 'finish'])->name('report.gazeboo.finish');
            Route::get('/decline', [\App\Http\Controllers\ReportGazebooController::class, 'decline'])->name('report.gazeboo.decline');
        });
    });

    Route::get('/server-busyness', [\App\Http\Controllers\ServerBusyController::class, 'index'])->name('server-busyness');

    Route::get('/service', [\App\Http\Controllers\ServiceController::class, 'index'])->name('service.index');

});

app/Models/Booking.php
<?php

namespace App\Models;

use App\Traits\WithPictures;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Booking extends Model
{
    use HasFactory, SoftDeletes, WithPictures;

    const PROCESS = "Proses";
    const BOOKED = "Booked";
    const DECLINE = "Ditolak";
    const FINISH = "Selesai";

    protected $fillable = [
        'booking_id',
        'status',
        'note',
        'booking_date',
        'booking_date_end',
        'booking_time',
        'booking_realization',
        'booking_time_approved',
        'gazeboo_id',
        'guest_id',
        'total_price',
        'booking_start',
        'booking_end'
    ];

    public function guest(){
        return $this->hasOne(Guest::class, 'id', 'guest_id')->withDefault();
    }

    public function gazeboo(){
        return $this->hasOne(Gazeboos::class, 'id', 'gazeboo_id');
    }

    public function serviceTime(){
        $start = Carbon::parse($this->created_at);
        $end = Carbon::parse($this->booking_time_approved);

        return $start->diffInMinutes($end).' Menit';
    }

    public function getStatusBadgeAttribute(){
        switch ($this->status){
            case self::PROCESS :
                return "<span class='badge badge-warning'>".self::PROCESS."</span>";
            case self::BOOKED :
                return "<span class='badge badge-secondary'>".self::BOOKED."</span>";
            case self::DECLINE :
                return "<span class='badge badge-danger'>".self::DECLINE."</span>";
            case self::FINISH :
                return "<span class='badge badge-success'>".self::FINISH."</span>";
            default :
                return "-";
        }
    }
}

app/Models/Pictures.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pictures extends Model
{
    use HasFactory;

    protected $fillable = [
        'pictureable_type',
        'pictureable_id',
        'file_name',
        'caption',
        'path'
    ];

    public function getUrlAttribute()
    {
        if (is_null($this->path)) {
            return asset('images/logo_watermark.jpg');
        }

        return asset('storage/'.$this->path.'/'.$this->file_name);
    }
}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use App\Exports\BookingExport;
use App\Models\Booking;
use App\Models\Gazeboos;
use App\Models\Guest;
use App\Models\Pictures;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class BookingController extends Controller
{
    public function index(){
        $indexLink = route('booking.index');
        $exportLink = route('booking.export');
        $createLink = route('booking.create');

        $bookings = Booking::latest()->paginate(10);

        return view('transaction.booking.index', compact('indexLink', 'exportLink', 'createLink', 'bookings'));
    }

    public function create(){
        $indexLink = route('booking.index');
        $storeLink = route('booking.store');

        $gazeboes = Gazeboos::active()->available()->get();

        return view('transaction.booking.create', compact('indexLink', 'storeLink', 'gazeboes'));
    }

    public function store(Request $request){
        $date = get_start_and_end_date($request->booking_date);
        $dateStart = $date['start_date'];
        $dateEnd = $date['end_date'];

        $diff = get_diff_days(Carbon::parse($dateStart)->subDay(), $dateEnd);

        $request->merge(['booking_date' => date("Y-m-d H:i:s", strtotime($request->booking_date))]);
        $gazeboo = Gazeboos::find($request->gazeboo_id);
        $count = Booking::withTrashed()->where('gazeboo_id', $request->gazeboo_id)->count();
        $price = $gazeboo->price * $diff;

        $booking_id = "GZB-".$gazeboo->number."-".sprintf('%06d', $count);

        $request['booking_id'] = $booking_id;
        $request['status'] = Booking::PROCESS;

        $guest = Guest::create($request->all());

        $booking = new Booking();
        $booking['booking_id'] = $booking_id;
        $booking['status'] = Booking::PROCESS;
        $booking['note'] = $request->note;
        $booking['booking_date'] = $dateStart ?? Carbon::parse($request->booking_date);
        $booking['booking_date_end'] = $dateEnd;
        $booking['gazeboo_id'] = $request->gazeboo_id;
        $booking['guest_id'] = $guest->id;
        $booking['total_price'] =$price;

        $booking->save();

        if(!empty($request->images)){
            insert_pictures($request->images, $booking);
        }

        return redirect()->route('booking.index');
    }

    public function edit(Booking $booking){
        $indexLink = route('booking.index');
        $updateLink = route('booking.update', $booking);

        $gazeboes = Gazeboos::active()->available()->get();

        return view('transaction.booking.edit', compact('indexLink', 'updateLink', 'gazeboes', 'booking'));
    }

    public function update(Request $request, Booking $booking){
        $guest = Guest::find($booking->guest->id);
        $guest->update($request->all());

        $booking->update($request->all());

        if (!empty($request->images_old)){
            foreach ($request->images_old as $key => $image){
                $picture = Pictures::find($request->id_images_old[$key]);
                \Illuminate\Support\Facades\Storage::disk('public')->put($picture->path, $image);

                $picture->update([
                    'file_name' => $image->hashName(),
                ]);
            }
        }

        if (isset($request->images)){
            insert_pictures($request->images, $booking);
        }

        return redirect()->route('booking.index');
    }

    public function destroy(Booking $booking){
        $booking->delete();

        return redirect()->back();
    }

    public function finish(Booking $booking){
        $booking->update([
            'status' => Booking::FINISH,
            'booking_end' => Carbon::now()
        ]);
        $booking->gazeboo()->update(['is_available' => 1]);

        return redirect()->back();
    }

    public function realization(Booking $booking){
        $booking->update([
            'booking_realization' => Carbon::now()
        ]);

        return redirect()->back();
    }

    public function approve(Booking $booking){
        $booking->update([
            'booking_time_approved' => Carbon::now(),
            'status' => Booking::BOOKED,
            'booking_start' => Carbon::now()
        ]);
        $booking->gazeboo()->update(['is_available' => 0]);

        return redirect()->back();
    }

    public function decline(Booking $booking){
        $booking->update(['status' => Booking::DECLINE]);

        return redirect()->back();
    }

    public function Export()
    {
        $bookings = Booking::all();
        $data = new BookingExport($bookings);
        return Excel::download($data, 'Booking.xlsx');
    }
}

resources/views/transaction/booking/edit.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Edit Booking : {{ ($booking->booking_id) }}</h1>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                    <div class="card">
                        <div class="card-body">

                            <form action="{{ $updateLink }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="gazeboo-id-input">Gazeboo</label>
                                            <select class="custom-select select2" id="gazeboo_id" name="gazeboo_id" required>
                                                @foreach($gazeboes as $gazeboo)
                                                    <option value="{{ $gazeboo->id }}" {{ $booking->gazeboo->id == $gazeboo->id ? 'selected':'' }}>#{{ $gazeboo->number }} - {{ \Illuminate\Support\Str::limit($gazeboo->title, 20, '...') }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="booking-date-input">Tanggal Booking</label>
                                            <input name="booking_date" class="form-control" type="datetime-local" value="{{ $booking->booking_date }}">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="name-input">Nama Pemesan</label>
                                            <input type="text" class="form-control" name="name" id="name-input" placeholder="" value="{{ @$booking->guest->name }}" autocomplete="off" required>
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="identity_number-input">Nomor KTP</label>
                                            <input type="text" class="form-control" name="identity_number" id="identity_number-input" placeholder="" value="{{@ $booking->guest->identity_number }}"  autocomplete="off" required>
                                        </div>
                                    </div>

                                    <div class="col-md-4">
                                        <div class="form-group">
                                            <label for="phone_number-input">Nomor Telephon</label>
                                            <input type="text" class="form-control" name="phone_number" id="phone_number-input" placeholder="" value="{{ @$booking->guest->phone_number }}"  autocomplete="off" required>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="address-input">Alamat</label>
                                        <textarea style="min-height: 50px" name="address" rows="10" class="form-control" id="address-input" required>{{ $booking->guest->address }}</textarea>
                                    </div>

                                    <div class="form-group">
                                        <label for="note-input">Keperluan</label>
                                        <textarea style="min-height: 120px" name="note" rows="10" class="form-control" id="note-input"  required>{{ $booking->note }}</textarea>
                                    </div>

                                    @for($x = 0; $x < count($booking->pictures); $x++)
                                        <div class="form-group col-xs-12 col-md-3">
                                            <input type="hidden" name="id_images_old[]" value="{{ $booking->pictures[$x]->id }}">
                                            <input type="file" name="images_old[{{ $x }}]" id="input-file-now" class="dropify" data-default-file="{{ $booking->pictures[$x]->url }}" accept="image/*"/>
                                            <a href="{{ route('gazeboo.delete-picture', $booking->pictures[$x]->id)}}" class="btn btn-danger btn-block mt-2">Hapus</a>
                                        </div>
                                    @endfor

                                    @for($i = count($booking->pictures); $i <= 3; $i++)
                                        <div class="form-group col-xs-12 col-md-3">
                                            <input type="file" name="images[]" id="input-file-now" class="dropify" accept="image/*"/>
                                        </div>
                                    @endfor

                                </div>
                                <a href="{{ $indexLink }}" type="button" class="btn btn-danger"><i class="fas fa-times"></i> Batal</a>
                                <button type="submit" class="btn btn-success"><i class="fas fa-paper-plane"></i> Kirim</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

@push('css')
    <link href="{{ asset('css/dropify.css') }}" rel="stylesheet">
@endpush
@push('javascript')
    <script src="{{ asset('js/dropify.min.js') }}"></script>
    <script>
        $(function () {
            $('.dropify').dropify();
        });
    </script>
@endpush

resources/views/transaction/booking/index.blade.php
@extends('layouts.app')

@section('title', 'Dashboard')

@section('content')
    <section class="section">
        <div class="section-header">
            <h1>Booking</h1>
        </div>

        <div class="section-body">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-12 col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-right mb-4">
                                <a href="{{ $exportLink }}" type="button" class="btn btn-primary"><i class="fas fa-file-excel"></i> Export</a>
                                <a href="{{ $createLink }}" type="button" class="btn btn-success"><i class="fas fa-plus"></i> Tambah</a>
                            </div>

                            <div class="table-responsive">
                                <table class="table">
                                    <thead class="thead-dark">
                                        <tr style="white-space: nowrap">
                                            <th scope="col">#</th>
                                            <th scope="col">Gazeboo</th>
                                            <th scope="col">Booking ID</th>
                                            <th scope="col">Pemesan</th>
                                            <th scope="col">No. Telp</th>
                                            <th scope="col">Alamat</th>
                                            <th scope="col">Keperluan</th>
                                            <th scope="col">Tanggal Booking</th>
                                            <th scope="col">Jam Kedatangan</th>
                                            <th scope="col">Jam Realisasi Kedatangan</th>
                                            <th scope="col">Total Bayar</th>
                                            <th scope="col">Status</th>
                                            <th scope="col">Bukti Booking</th>
                                            <th scope="col" class="text-center"><i class="fas fa-cog fa-spin"></i> Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($bookings as $key => $booking)
                                            <tr>
                                                <td>{{ $key + 1 + (((request('page') ?? 1) - 1) * 10) }}</td>
                                                <td>{{ $booking->gazeboo->number }}</td>
                                                <td><span style="white-space: nowrap">{{ $booking->booking_id }}</span></td>
                                                <td><span style="white-space: nowrap">{{ @$booking->guest->name }}</span></td>
                                                <td>{{ @$booking->guest->phone_number }}</td>
                                                <td>{{ @$booking->guest->address }}</td>
                                                <td>{{ $booking->note }}</td>
                                                <td style="white-space: nowrap">{{ parse_date($booking->booking_date) }}</td>
                                                <td style="white-space: nowrap">{{ parse_time_hm($booking->booking_time) }}</td>
                                                <td style="white-space: nowrap">{{ parse_time_hm($booking->booking_realization) }}</td>
                                                <td>{{ rp_format($booking->total_price) }}</td>
                                                <td class="text-center">{!! $booking->status_badge !!}</td>
                                                <td>
                                                    @foreach($booking->pictures as $picture)
                                                        <a href="{{ $picture->url }}" target="_blank"><img src="{{ $picture->url }}" class="img-thumbnail m-1" style="width:50px; display: inline-block"></a>
                                                    @endforeach
                                                </td>
                                                <td style="white-space: nowrap">
                                                    @if($booking->status == \App\Models\Booking::PROCESS)

                                                        <a href="{{ route('booking.approve',$booking) }}" class="btn btn-success mb-1"><i class="fas fa-check"></i></a>
                                                        <a href="{{ route('booking.decline',$booking) }}" class="btn btn-danger mb-1"><i class="fas fa-times"></i></a>
                                                        <a href="{{ route('booking.edit',$booking) }}" class="btn btn-warning mb-1"><i class="fas fa-pen"></i></a>

                                                        <form action="{{ route('booking.delete', $booking) }}" method="POST" onsubmit="return confirm('Anda yakin menghapus data ini?')" style="display: inline !important;">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="btn btn-danger"><i class="fas fa-trash"></i></button>
                                                        </form>
                                                    @endif

                                                    @if($booking->booking_time_approved)
                                                        <a href="{{ route('booking.realization',$booking) }}" class="btn btn-primary mb-1"><i class="fas fa-clock"></i></a>
                                                    @endif

                                                    @if($booking->status == \App\Models\Booking::BOOKED)
                                                        <a href="{{ route('booking.finish',$booking) }}" class="btn btn-success mb-1"><i class="fas fa-check"></i></a>
                                                    @endif
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="float-right">
                                {{ $bookings->appends(Request::except('page'))->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection